name: CI

on:
  # Triggers on any branch that opens a pull request.
  pull_request:
    branches:
      - "*"
    # This action is not triggered when markdown files are modified.
    paths-ignore:
      - '**.md'
  # Triggers on push to the following branches
  push:
    branches:
      - "main"
      - "dev"
    # This action is not triggered when markdown files are modified.
    paths-ignore:
      - '**.md'

env:
  # Permissions env
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # General env
  MIX_ENV: test
  ELIXIR_VERSION: 1.14.2
  OTP_VERSION: 25.1.2

jobs:
  dev:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Development Checks
        uses: ./.github/actions/dev
        with:
          ELIXIR_VERSION: ${{ env.ELIXIR_VERSION }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          MIX_ENV: dev
          OTP_VERSION: ${{ env.OTP_VERSION }}

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Unit Tests
        uses: ./.github/actions/test
        with:
          ELIXIR_VERSION: ${{ env.ELIXIR_VERSION }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          MIX_ENV: test
          OTP_VERSION: ${{ env.OTP_VERSION }}
